version: "3.8"

services:
  mongodb1:
    image: mongo:latest
    container_name: mongodb1
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: vic
      MONGO_INITDB_ROOT_PASSWORD: vic
      MONGO_INITDB_DATABASE: admin
    volumes:
      - "./data-mongo1:/data/db"
